[sources.filesystem]  
#bucket_url = "/Users/abhinavkumar/Downloads/employees.csv" #when running/Loading the employees dataset or working with employees data set --use this
bucket_url = "/Users/abhinavkumar/Downloads/fee_transaction.csv" #when running/Loading the feee_transaction data set --use this

dlthub_telemetry = true